### ISSUE TITLE
Erlang code of "Poker hands" problem

### ISSUE THREAD

**Issue by AlbertMoscow** [gvaughn/elixir_kata#1]
Hi!

I've found this Erlang solution of Euler's problem 54 "Poker hands", that seems to me very inspiring:

-module(problem54_poker).

-compile([export_all]).

-define(HC,0). %    High Card: Highest value card.
-define(OP,1). %    One Pair: Two cards of the same value.
-define(TP,2). %    Two Pairs: Two different pairs.
-define(TK,3). %    Three of a Kind: Three cards of the same value.
-define(ST,4). %    Straight: All cards are consecutive values.
-define(FL,5). %    Flush: All cards of the same suit.
-define(FH,6). %    Full House: Three of a kind and a pair.
-define(FK,7). %    Four of a Kind: Four cards of the same value.
-define(SF,8). %    Straight Flush: All cards are consecutive values of same suit.

problem54_poker() ->
  {ok,F} = file:open("C:\erl5.10.1\bin\poker.txt",[read]),
  R = problem54_poker(F,file:read_line(F),0),
  file:close(F),
  R.

problem54_poker(_,eof,I) -> I;
problem54_poker(F,{ok,D},I) -> problem54_poker(F,file:read_line(F),I+readline(D)).

readline(S) ->
  {S1,S2} = lists:split(15, S),
  case (readline(S1,[],undefined) > readline(S2,[],undefined)) of
    false -> 0;
    true -> 1
  end.

readline([],R,Colour) -> hand({lists:sort(R),Colour =/= false});
readline([C,K,_|Q],R,K) -> readline(Q,[convert(C)|R],K);
readline([C,K,_|Q],R,undefined) -> readline(Q,[convert(C)|R],K);
readline([C,_,_|Q],R,_) -> readline(Q,[convert(C)|R],false).

convert($2) -> 2;
convert($3) -> 3;
convert($4) -> 4;
convert($5) -> 5;
convert($6) -> 6;
convert($7) -> 7;
convert($8) -> 8;
convert($9) -> 9;
convert($T) -> 10;
convert($J) -> 11;
convert($Q) -> 12;
convert($K) -> 13;
convert($A) -> 14.

hand({[A,A,A,A,_],_}) -> {?FK,A};
hand({[_,A,A,A,A],_}) -> {?FK,A};
hand({[B,B,A,A,A],_}) -> {?FH,A};
hand({[A,A,A,B,B],_}) -> {?FH,A};
hand({[A,A,A,_,_],_}) -> {?TK,A};
hand({[_,A,A,A,_],_}) -> {?TK,A};
hand({[_,_,A,A,A],_}) -> {?TK,A};
hand({[_,B,B,A,A],_}) -> {?TP,A};
hand({[B,B,_,A,A],_}) -> {?TP,A};
hand({[B,B,A,A,_],_}) -> {?TP,A};
hand({[A,A,_,_,_],_}) -> {?OP,A};
hand({[_,A,A,_,_],_}) -> {?OP,A};
hand({[_,_,A,A,_],_}) -> {?OP,A};
hand({[_,_,_,A,A],_}) -> {?OP,A};
hand({[2,3,4,5,14],true}) -> {?SF,5};
hand({[2,3,4,5,14],false}) -> {?ST,5};
hand({[A,_,_,_,B],true}) when (B-A) == 4 -> {?SF,B};
hand({[A,_,_,_,B],false}) when (B-A) == 4 -> {?ST,B};
hand({[_,_,_,_,A],true}) -> {?FL,A};
hand({[_,_,_,_,A],_}) -> {?HC,A}.

**Comment by gvaughn** [comment]
That's nice. I wanted to use more pattern matching in my solution, but I needed the more statistical approach to handle tiebreakers. I don't think this version does that.

**Comment by AlbertMoscow** [comment]
It passes these two tests:

test "using tiebreakers pair of 3s beat a pair of 2s" do
    assert Poker.winner("3C 3H 5C 7D 9S 2C 2H 5S 7C AH") == 1
  end

  test "using tiebreakers ace-high beats king-high" do
    assert Poker.winner("AC 2H 4C 6D 8S KH 2C 4H 6C 8H") == 1
  end

but this one cannot:

  test "using tiebreakers pairs use kicker" do
    assert Poker.winner("8H 8S AC 2S 3D 8C 8D KD 9S 2C") == 1
  end

**Comment by gvaughn** [comment]
Yes, my understanding of erlang syntax is imperfect, but it looks like it ultimately uses just 2 values to compare the hands. The "type" of the hand (1 pair, 2 pair, full house, etc.) and 1 leading card value. It's when the hands are different in the 2nd tiebreaking value that it fails. It should also fail for

test "using tiebreakers full house (ace over 10) beats full house (ace over 9) in either order" do
assert Poker.winner("AD AS TH TC TH AC AH 9C 9D 9S") == 1
assert Poker.winner("AC AH 9C 9D 9S AD AS TH TC TH") == 2
end

**Comment by gvaughn** [comment]
Oops, that was a bad example above. You can't really have 2 players with full houses with the same primary tiebreaker. It would require 6 aces. That would be a crooked poker game :-)  And I didn't specify it correctly anyway. I know I could come up with more failures of that erlang code. I'll try to find more time later on.

**Comment by AlbertMoscow** [comment]
Ok. :) BTW, did you write your tests after writing the code? TDD approach requires you write tests first, fail them, then write code to pass them, then refactor the code. If you're interested to see an example, I've recorded a small video on this topic here: http://youtu.be/TPcVx2yON-4

**Comment by gvaughn** [comment]
Thanks. I actually watched your video the other day. I forgot where I found the link. Nicely done.

In my case, I've been practicing TDD for 15 years, but my goal here was not further practice of that, but learning Elixir syntax, so, yeah, the tests were done afterward. However, the original ruby implementation in which I derived this algorithm was developed test first :-)

**Comment by AlbertMoscow** [comment]
Wow! Thank you. :) There is also an excellent article written by Dave Thomas about how functional thinking during elixir programming differs from imperative one:
http://pragprog.com/magazines/2013-07/programming-elixir

**Comment by gvaughn** [comment]
Thanks. I've read that series, and read Dave's book twice. He actually provided the code for Poker.Card.from_string on elixir-lang-talk

**Comment by AlbertMoscow** [comment]
Hi! :)

Wouldn't you like to solve in elixir also the problem # 96 "Sudoku" from Euler's project?
http://projecteuler.net/problem=96

**Comment by gvaughn** [comment]
That looks like an ... ugly problem. I'm actually thinking that the next time I can find the time, I want to explore OTP. There's an elevator exercise to simulate a bank of 2..n elevators (but I can't find a direct link now). I tried it once in Ruby at a local user group and realized it is inherently concurrent.
